version: '3.2'

services:
  dashboard:
    build:
      context: ./dashboard
    volumes:
      - ./dashboard:/var/dashboard
    ports:
      - "3030:3030"
  api:
    build:
      context: ./api
    volumes:
      - ./api:/var/app
    ports:
      - "3000:3000"
  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d/